### ISSUE TITLE
Golint warnings

### ISSUE THREAD

**Issue by rogeriozambon** [opentogo/togo#1]
All warnings can be viewed [here](https://goreportcard.com/report/github.com/opentogo/togo) in `golint` section and no need to submit all at once. Do as you can! 😃

**Comment by JonLim** [comment]
@rogeriozambon I can tackle a few of them! Will get a PR up soon.

**Comment by rogeriozambon** [comment]
@JonLim, thanks for your help!

**Comment by rogeriozambon** [comment]
#2

**Comment by rogeriozambon** [comment]
@JonLim and @hoop33, thanks for #2 and #3. You guys are awesome!
